### ISSUE TITLE
How to setup "sticky-states" with views

### ISSUE THREAD

**Issue by buksy90** [ui-router/sticky-states#24] opened 2018-01-16 15:13 UTC
Hello,

At my work we have a large application using ng1 + ui-router. Our application consists of tens of widgets implemented into view of parent state/page. Each widget displays some charts/tables and requests data on start (those requests are slow because of lot of data). So we wanted to use sticky states to preserve widget state when users goes to another widget and then back. Unfortunately, it doesnt work as expected.

[Here is a simple example](http://jsbin.com/lohasefoza/5/edit?js,output), the problem is:
1. when in sticky1 or sticky2 state, it is not possible to go to other sticky state (transitions returns "success" but its not working).
2. when going from any sticky state to home and then back to sticky, the state of sticky is not preserved.

Even though, this looks like bugs to me, I guess those are not and this is just not intended way to use the sticky-states. Is there any way how to make this work?

Thank you

**Comment by poindexd** [comment] 2018-01-17 06:05
+1

**Comment by soroushNeshat** [comment] 2018-01-18 14:09
of course it wont change unless u exit the parent state . a sticky state is sticky . it cant be removed until parent is exited . problem is that you are sharing `ui-view='view1'` for both of the sticky states . u have to create a `ui-view` for each widget like this : 

<pre>
ui-view='widget1'
ui-view='widget2'
ui-view='widget3'<pre>

**Comment by buksy90** [comment] 2018-01-23 13:41
Unfortunately that is not possible in current project :/.

From my point of view, the ideal workflow for sticky states would be something like this (pseudo):

```
state_entered() {
  #create scope
  if(cache[state.name]) scope = cache[state.name].scope
  else scope = $rootScope.new();

  #create controller
  if(cache[state.name]) controller = cache[state.name].controller
  else scope = $controller(state.controller, ctrlOptions);

  #compile 
  link = $compile(element);

  return link(scope);
}
```

I tried to create a ui-router plugin for this with a little ui-router modification. I modified ui-router to use own service for creating scope and controller. [Here is the diff](https://www.diffchecker.com/6nIGFLl8) .
[Here is jsbin](http://jsbin.com/xixeximeqo/edit?html,js,output) playground with changed ui-router and plugin implementation. Unfortunately it doesnt work. It does display each state first time. When state is entered again, scope and controller are returned from cache, but the template doesnt get compiled and Im not sure why :(.

I thought this might be alternative to sticky-states but not sure how to fix this. I think the problem is with scope not being handled properly by ui-router. I tried to suppress $destroy event but it doesnt work anyway. :(

**Comment by nandakumar531** [comment] 2018-02-20 07:53
Hello @christopherthielen ,

we are also getting the same issue where @buksy90 got.

using `ng1 (1.6.1)` + `angular-ui-router@1.0.11`+ `uirouter/core@5.0.11` + `uirouter/sticky-states@1.4.1` + `uirouter/dsr@1.0.2`

In different scenarios, the stickiness is failing.

1. Same as @buksy90 mentioned.
2. [Here is another example](https://plnkr.co/edit/IO7M1HCNeTPlJrtxXcGW)
    three tabs used in the above example. home, about and deepnest. The deepnest tab is decorated with `sticky: true` . Between home and about tabs the state transition is working fine because there is no stickiness is applied. But when user clicks the deepnest tab and come back to home or about tabs, transitions returns "success" but deepnest view is showing. The about or home view is not updating.

With `ui-router-extras` the sticky state functionality working fine. But when we upgrade it to latest `uirouter/sticky-states@1.4.1 `  then we are facing the above issues. Even I checked with all the ui-router latest versions the same issue persists.

Are these issues addressed in coming versions?

**Comment by nandakumar531** [comment] 2018-02-22 14:38
@buksy90  is this issue resolved to you?

**Comment by buksy90** [comment] 2018-02-23 07:36
Hello @nandakumar531, no I havent found any solution yet. 

@christopherthielen could you please share any info on whether this functionality has been ever considered? If so, what is the reasons it hasn't been implemented?

**Comment by SadhanaNukala** [comment] 2018-03-06 07:46
@christopherthielen Can you please let us know when this issue will be fixed. 
attaching the above example which @buksy90  mentioned again for reference : http://jsbin.com/lohasefoza/5/edit?js,output

**Comment by xDisfigure** [comment] 2018-07-05 09:10
I'm not sure but check this out : DeepStateRedirect in ui-router extra plugins maybe that will solve your problem

**Comment by phuyem** [comment] 2018-07-15 12:04
My issue is quite similar. 

We have sticky on moduleA.home, from there url to moduleA.something won't navigate. The controller of something is not even fired. Note that moduleA is just an abstract state.

- deepStateRedirect = true won't help.
- remove sticky make things work smoothly.

**Comment by joniruokamo** [comment] 2018-08-03 05:57
This is bugging me as well. Any solution in sight?

**Comment by christopherthielen** [comment] 2018-08-03 21:30
This behavior is working as designed and isn't going to change.  As mentioned by @soroushNeshat in https://github.com/ui-router/sticky-states/issues/24#issuecomment-358657022 and in  [the documentation](
https://github.com/ui-router/sticky-states#2-mark-a-state-as-sticky) states, 

> The sticky state's view must have its own unique ui-view (not shared by other states). Create and target a named ui-view.

This limitation is by design and can't be changed.  Proposed work arounds such as trying to save and restore components manually would be prone to many edge cases and is not something I'm willing to support.  Further, those solutions would only work for one framework (i.e., AngularJS) where as the sticky states approach works for all frameworks (i.e., React, Angular, AngularJS)

So, the answer to this issue is: use named `ui-view` and target the named `ui-view` in the sticky state.  Show and hide the `ui-view` when the state is active/inactive.

**Closed by christopherthielen** 2018-08-03 21:30 UTC
